<?php
/**
 * Data layer for Blockophon colophon block.
 *
 * @package Blockophon
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Returns colophon data, reading from the cached option or generating fresh.
 *
 * @return array<string,mixed>
 */
function blockophon_get_data(): array {
	$cached = get_option( 'blockophon_colophon_data', false );
	if ( false !== $cached && is_array( $cached ) ) {
		return $cached;
	}
	return blockophon_generate_and_store_data();
}

/**
 * Generates fresh colophon data and persists it as a non-autoloaded option.
 *
 * @return array<string,mixed>
 */
function blockophon_generate_and_store_data(): array {
	$theme  = wp_get_theme();
	$parent = $theme->parent();

	require_once ABSPATH . 'wp-admin/includes/plugin.php';

	$all_plugins    = get_plugins();
	$active_paths   = (array) get_option( 'active_plugins', array() );
	$active_plugins = array_intersect_key( $all_plugins, array_flip( $active_paths ) );

	$mu_plugins = get_mu_plugins();

	$dropin_list    = _get_dropins();
	$active_dropins = array_filter(
		$dropin_list,
		static function ( array $dropin ): bool {
			return file_exists( WP_CONTENT_DIR . '/' . $dropin[0] );
		}
	);

	$settings = wp_get_global_settings();
	$styles   = wp_get_global_styles();

	$font_families = $settings['typography']['fontFamilies']['theme'] ?? array();

	$raw_body_font    = $styles['typography']['fontFamily'] ?? null;
	$raw_heading_font = $styles['elements']['heading']['typography']['fontFamily'] ?? null;

	$data = array(
		'customizations' => blockophon_get_customization_data(),
		'theme'          => array(
			'name'              => $theme->get( 'Name' ),
			'version'           => $theme->get( 'Version' ),
			'author'            => wp_strip_all_tags( (string) $theme->get( 'Author' ) ),
			'author_uri'        => $theme->get( 'AuthorURI' ),
			'theme_uri'         => $theme->get( 'ThemeURI' ),
			'is_child'          => (bool) $parent,
			'parent_name'       => $parent ? $parent->get( 'Name' ) : null,
			'parent_author'     => $parent ? wp_strip_all_tags( (string) $parent->get( 'Author' ) ) : null,
			'parent_author_uri' => $parent ? $parent->get( 'AuthorURI' ) : null,
		),
		'plugins'        => $active_plugins,
		'mu_plugins'     => $mu_plugins,
		'drop_ins'       => $active_dropins,
		'colors'         => $settings['color']['palette']['theme'] ?? array(),
		'font_families'  => $font_families,
		'font_sizes'     => $settings['typography']['fontSizes']['theme'] ?? array(),
		'body_font'      => blockophon_resolve_font_name( $raw_body_font, $font_families ),
		'heading_font'   => blockophon_resolve_font_name( $raw_heading_font, $font_families ),
	);

	update_option( 'blockophon_colophon_data', $data, false );
	return $data;
}

/**
 * Resolves a CSS custom property font reference to a human-readable font name.
 *
 * @param string|null                     $css_value     CSS custom property, e.g. "var(--wp--preset--font-family--canela)".
 * @param array<int,array<string,string>> $font_families Theme.json fontFamilies list.
 * @return string|null
 */
function blockophon_resolve_font_name( ?string $css_value, array $font_families ): ?string {
	if ( null === $css_value ) {
		return null;
	}
	if ( preg_match( '/var\(--wp--preset--font-family--([^)]+)\)/', $css_value, $m ) ) {
		$slug = $m[1];
		foreach ( $font_families as $family ) {
			if ( isset( $family['slug'] ) && $family['slug'] === $slug ) {
				return $family['name'] ?? null;
			}
		}
	}
	return null;
}

/**
 * Returns data about user-made customizations to templates and global styles.
 *
 * A template is considered customized when a DB record exists for it and
 * the record was not auto-generated by WordPress (i.e. is_wp_suggestion is false).
 *
 * @return array{
 *   modified_template_count: int,
 *   modified_part_count: int,
 *   modified_template_slugs: string[],
 *   modified_part_slugs: string[],
 *   has_custom_global_styles: bool,
 *   has_custom_css: bool,
 *   is_customized: bool
 * }
 */
function blockophon_get_customization_data(): array {
	$all_templates = get_block_templates( array(), 'wp_template' );
	$all_parts     = get_block_templates( array(), 'wp_template_part' );

	$modified_templates = array_values(
		array_filter(
			$all_templates,
			static function ( WP_Block_Template $t ): bool {
				// WP 7.0 sets is_custom=false for all standard template slugs (single, archive, etc.)
				// regardless of is_wp_suggestion meta. Read the meta directly to distinguish
				// user-saved templates from WP auto-generated suggestions.
				return 'custom' === $t->source && ! get_post_meta( (int) $t->wp_id, 'is_wp_suggestion', true );
			}
		)
	);

	$modified_parts = array_values(
		array_filter(
			$all_parts,
			static function ( WP_Block_Template $t ): bool {
				return 'custom' === $t->source && ! get_post_meta( (int) $t->wp_id, 'is_wp_suggestion', true );
			}
		)
	);

	$has_custom_global_styles = blockophon_detect_custom_global_styles();
	$has_custom_css           = '' !== trim( (string) wp_get_custom_css() );

	$modified_template_count = count( $modified_templates );
	$modified_part_count     = count( $modified_parts );

	return array(
		'modified_template_count'  => $modified_template_count,
		'modified_part_count'      => $modified_part_count,
		'modified_template_slugs'  => array_map( static fn( WP_Block_Template $t ): string => $t->slug, $modified_templates ),
		'modified_part_slugs'      => array_map( static fn( WP_Block_Template $t ): string => $t->slug, $modified_parts ),
		'has_custom_global_styles' => $has_custom_global_styles,
		'has_custom_css'           => $has_custom_css,
		'is_customized'            => $modified_template_count > 0 || $modified_part_count > 0 || $has_custom_global_styles || $has_custom_css,
	);
}

/**
 * Returns true when the site has a non-empty wp_global_styles post,
 * indicating the user has adjusted colors, typography, or other theme.json values.
 *
 * @return bool
 */
function blockophon_detect_custom_global_styles(): bool {
	$posts = get_posts(
		array(
			'numberposts' => 1,
			'post_status' => array( 'publish', 'draft' ),
			'post_type'   => 'wp_global_styles',
			'orderby'     => 'ID',
			'order'       => 'ASC',
		)
	);

	if ( empty( $posts ) ) {
		return false;
	}

	$content = trim( $posts[0]->post_content );
	if ( '' === $content || '{}' === $content ) {
		return false;
	}

	$decoded = json_decode( $content, true );
	return is_array( $decoded ) && ! empty( $decoded );
}

/**
 * Clears the cached colophon data and immediately rebuilds it.
 *
 * @return void
 */
function blockophon_refresh_cache(): void {
	delete_option( 'blockophon_colophon_data' );
	blockophon_get_data();
}
add_action( 'switch_theme', 'blockophon_refresh_cache' );
add_action( 'activated_plugin', 'blockophon_refresh_cache' );
add_action( 'deactivated_plugin', 'blockophon_refresh_cache' );
add_action( 'save_post_wp_template', 'blockophon_refresh_cache' );
add_action( 'save_post_wp_template_part', 'blockophon_refresh_cache' );
add_action( 'save_post_wp_global_styles', 'blockophon_refresh_cache' );

add_action(
	'upgrader_process_complete',
	static function ( $upgrader, array $hook_extra ): void {
		$type = $hook_extra['type'] ?? '';
		if ( in_array( $type, array( 'plugin', 'theme' ), true ) ) {
			blockophon_refresh_cache();
		}
	},
	10,
	2
);

add_action(
	'deleted_post',
	static function ( int $post_id, WP_Post $post ): void {
		if ( in_array( $post->post_type, array( 'wp_template', 'wp_template_part', 'wp_global_styles' ), true ) ) {
			blockophon_refresh_cache();
		}
	},
	10,
	2
);
