name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    name: Lint & Static Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: lts/*
          cache: npm

      - uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # v2
        with:
          php-version: '8.3'
          tools: composer
          coverage: none

      - name: Install Node dependencies
        run: npm ci

      - name: Install Composer dependencies
        run: composer install --no-progress --no-interaction

      - name: Build
        run: npm run build

      - name: JS & CSS lint
        run: npm run lint

      - name: PHP coding standards
        run: composer phpcs

      - name: PHPStan
        run: composer phpstan

  test:
    name: PHP Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: lts/*
          cache: npm

      - uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # v2
        with:
          php-version: '8.3'
          tools: composer
          coverage: none

      - name: Install Node dependencies
        run: npm ci

      - name: Install Composer dependencies
        run: composer install --no-progress --no-interaction

      - name: Start wp-env
        run: npx wp-env start

      - name: Run PHP tests
        run: npm run test:php

  plugin-check:
    name: Plugin Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: lts/*
          cache: npm

      - name: Install Node dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - uses: wordpress/plugin-check-action@98a1788320d0add90df2d8183934ecccbc4e05d2 # v1
        with:
          build-dir: '.'
          wp-version: latest
